In [1]:
import pandas as pd
import imdb_api as ia

In [2]:
def clean_currency(x):
    """ If the value is a string, then remove currency symbol and delimiters
    otherwise, the value is numeric and can be converted
    """
    if isinstance(x, str):
        return(x.replace('$', '').replace(',', ''))
    return(x)

In [609]:
def fix_chars(df):
    dictionary = {'â':'\'', 'Ã©':'é', 'â¦':'... ', 'â':' - ', 'Ã¨':'è'}
    df['Title'].replace(dictionary,regex=True, inplace=True)

In [3]:
imdbtitle_df = pd.read_csv('./data/test/title.basics.tsv', sep='\t',encoding='utf-8',dtype='str')

In [4]:
imdbnames_df = pd.read_csv('./data/test/name.basics.tsv', sep='\t',encoding='utf-8')

In [589]:
imdbprinciplas_df = pd.read_csv('./data/test/title.principals.tsv', sep='\t',encoding='utf-8')

In [546]:
nb_df = pd.read_csv('./data/thenum_tidy.csv', encoding='utf-8')

In [587]:
imdbnames_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11144485 entries, 0 to 11144484
Data columns (total 6 columns):
 #   Column             Dtype
---  ------             -----
 0   nconst             object
 1   primaryName        object
 2   birthYear          object
 3   deathYear          object
 4   primaryProfession  object
 5   knownForTitles     object
dtypes: object(6)
memory usage: 510.2+ MB

In [7]:
colstoclean = ['ProductionBudget', 'Opening WeekendTheaters',
       'MaximumTheaters', 'TheatricalEngagements', 'Opening WeekendRevenue',
       'DomesticBox Office', 'Infl. Adj. Dom.Box Office',
       'InternationalBox Office', 'WorldwideBox Office']
for col in colstoclean:
    nb_df[col] = nb_df[col].apply(clean_currency).astype('float')

In [8]:
nb_df = nb_df[nb_df['DomesticBox Office'] !=0]

In [549]:
nb_df.drop(columns=['Unnamed: 0'],inplace=True)

In [536]:
nb_df.to_csv('./data/thenum_tidy.csv', encoding='utf-8')

In [307]:
nb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2499 entries, 0 to 2498
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Released                   2499 non-null   int64
 1   ReleasedWorldwide          2499 non-null   int64
 2   Title                      2499 non-null   object
 3   TheatricalDistributor      2484 non-null   object
 4   Genre                      2489 non-null   object
 5   Source                     2476 non-null   object
 6   ProductionMethod           2487 non-null   object
 7   CreativeType               2473 non-null   object
 8   ProductionBudget           2499 non-null   float64
 9   Opening WeekendTheaters    2499 non-null   float64
 10  MaximumTheaters            2499 non-null   float64
 11  TheatricalEngagements      2499 non-null   float64
 12  Opening WeekendRevenue     2499 non-null   float64
 13  DomesticBox Office         2499 non-null   float64
 14  Infl. Adj. Dom.Box Office  2499 non-null   float64
 15  InternationalBox Office    2499 non-null   float64
 16  WorldwideBox Office        2499 non-null   float64
dtypes: float64(9), int64(2), object(6)
memory usage: 332.0+ KB

In [436]:
imdbmovietitles_df = imdbtitle_df.loc[imdbtitle_df['titleType']  == 'movie']

In [440]:
imdbmovietitles_df = imdbmovietitles_df.loc[imdbmovietitles_df['startYear']  != '\\N']

In [441]:
imdbmovietitles_df = imdbmovietitles_df.loc[imdbmovietitles_df['startYear'].astype(int)  >= 2010]

In [442]:
imdbmovietitles_df

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,titleTypeLower,primaryTitleLower
11059,tt0011216,movie,Spanish Fiesta,La fête espagnole,0,2019,\N,67,Drama,movie,spanish fiesta
11636,tt0011801,movie,Tötet nicht mehr,Tötet nicht mehr,0,2019,\N,\N,"Action,Crime",movie,tötet nicht mehr
16657,tt0016906,movie,Frivolinas,Frivolinas,0,2014,\N,80,"Comedy,Musical",movie,frivolinas
19701,tt0019996,movie,Hongxia,Hongxia,0,2011,\N,94,Action,movie,hongxia
61126,tt0062336,movie,The Tango of the Widower and Its Distorting Mirror,El Tango del Viudo y Su Espejo Deformante,0,2020,\N,70,Drama,movie,the tango of the widower and its distorting mirror
...,...,...,...,...,...,...,...,...,...,...,...
8168750,tt9916538,movie,Kuambil Lagi Hatiku,Kuambil Lagi Hatiku,0,2019,\N,123,Drama,movie,kuambil lagi hatiku
8168791,tt9916622,movie,Rodolpho Teóphilo - O Legado de um Pioneiro,Rodolpho Teóphilo - O Legado de um Pioneiro,0,2015,\N,57,Documentary,movie,rodolpho teóphilo - o legado de um pioneiro
8168830,tt9916706,movie,Dankyavar Danka,Dankyavar Danka,0,2013,\N,\N,Comedy,movie,dankyavar danka
8168841,tt9916730,movie,6 Gunn,6 Gunn,0,2017,\N,116,\N,movie,6 gunn
8168852,tt9916754,movie,Chico Albuquerque - Revelações,Chico Albuquerque - Revelações,0,2013,\N,49,Documentary,movie,chico albuquerque - revelações

In [483]:

imdbmovietitles_df.drop(columns=['titleTypeLower', 'isAdult', 'genres'], inplace=True)

In [58]:
dictionary = {'â':'\'', 'Ã©':'é', 'â¦':'... ', 'â':' - ', 'Ã¨':'è'}
nb_df['Title'].replace(dictionary,regex=True, inplace=True)

In [550]:
nb_df['Title'].replace(to_replace='Des Hommes et Des Dieux', value='Of Gods and Men',regex=True,inplace=True)
nb_df['TitleLower'] = nb_df['Title'].str.lower()
imdbmovietitles_df['primaryTitleLower'] = imdbmovietitles_df['primaryTitle'].str.lower()
merged_df = pd.merge(nb_df, imdbmovietitles_df.loc[imdbmovietitles_df['titleType']=='movie'],  how='left', left_on=['TitleLower'], right_on = ['primaryTitleLower'])
merged_df.loc[merged_df.tconst.isna()]['WorldwideBox Office'].max()

86787530.0

In [570]:
merged_df.loc[merged_df.tconst.isna()]['WorldwideBox Office'].mean()

15191995.34375

In [568]:
merged_df.loc[merged_df.tconst.isna()].sort_values(by=['WorldwideBox Office'],ascending=False)

,Unnamed: 0,Released,ReleasedWorldwide,Title,TheatricalDistributor,Genre,Source,ProductionMethod,CreativeType,ProductionBudget,...,WorldwideBox Office,TitleLower,tconst,titleType,primaryTitle,originalTitle,startYear,endYear,runtimeMinutes,primaryTitleLower
15,15,2010,2010,Océans,Walt Disney,Documentary,Based on Real Life Events,Live Action,Factual,80000000.0,...,86787530.0,océans,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,68,2011,2011,Spy Kids: All the Time in the World,Weinstein/Dimension,Adventure,Original Screenplay,Live Action,Kids Fiction,27000000.0,...,80681183.0,spy kids: all the time in the world,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1209,1273,2017,2017,Victoria and Abdul,Focus Features,Drama,Based on Factual Book/Article,Live Action,Dramatization,21000000.0,...,68271146.0,victoria and abdul,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2604,3460,2018,2018,CafarnaÃºm,Sony Pictures Classics,Drama,Original Screenplay,Live Action,Contemporary Fiction,4000000.0,...,65233793.0,cafarnaãºm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1753,1822,2012,2012,Silent Hill: Revelation 3D,Open Road,Horror,Based on Game,Live Action,Fantasy,20000000.0,...,55975672.0,silent hill: revelation 3d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1579,1644,2010,2010,Don McKay,NaN,NaN,NaN,NaN,NaN,6000000.0,...,13722.0,don mckay,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
491,554,2010,2010,The Living Wake,Mangusta Productions,NaN,NaN,NaN,NaN,500000.0,...,12232.0,the living wake,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1580,1645,2010,2010,Jerusalema,Anchor Bay Entertainment,Action,Original Screenplay,Live Action,Historical Fiction,2000000.0,...,10679.0,jerusalema,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1708,1775,2011,2011,Tanner Hall,Anchor Bay Entertainment,Drama,Original Screenplay,Live Action,Contemporary Fiction,3000000.0,...,5073.0,tanner hall,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2245,2317,2015,2015,Childless,Monterey Media,Drama,Original Screenplay,Live Action,Contemporary Fiction,1000000.0,...,1036.0,childless,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [564]:
merged_df.drop_duplicates(inplace=True)

In [565]:
merged_df.sort_values(by=['Title'],ascending=True)

,Unnamed: 0,Released,ReleasedWorldwide,Title,TheatricalDistributor,Genre,Source,ProductionMethod,CreativeType,ProductionBudget,...,WorldwideBox Office,TitleLower,tconst,titleType,primaryTitle,originalTitle,startYear,endYear,runtimeMinutes,primaryTitleLower
1056,1120,2016,2016,10 Cloverfield Lane,Paramount Pictures,Thriller/Suspense,Original Screenplay,Live Action,Contemporary Fiction,15000000.0,...,1.082864e+08,10 cloverfield lane,tt1179933,movie,10 Cloverfield Lane,10 Cloverfield Lane,2016.0,\N,103,10 cloverfield lane
2237,2309,2015,2015,10 Days in a Madhouse,Cafe Pictures,Drama,Original Screenplay,Live Action,Dramatization,12000000.0,...,1.461600e+04,10 days in a madhouse,tt3453052,movie,10 Days in a Madhouse,10 Days in a Madhouse,2015.0,\N,111,10 days in a madhouse
2552,3408,2018,2018,12 Strong,Warner Bros.,Drama,Based on Factual Book/Article,Live Action,Historical Fiction,35000000.0,...,7.111838e+07,12 strong,tt1413492,movie,12 Strong,12 Strong,2018.0,\N,130,12 strong
1863,1933,2013,2013,12 Years a Slave,Fox Searchlight,Drama,Based on Factual Book/Article,Live Action,Historical Fiction,20000000.0,...,1.807651e+08,12 years a slave,tt2024544,movie,12 Years a Slave,12 Years a Slave,2013.0,\N,134,12 years a slave
1493,1558,2010,2010,127 Hours,Fox Searchlight,Drama,Based on Real Life Events,Live Action,Dramatization,18000000.0,...,6.021717e+07,127 hours,tt1542344,movie,127 Hours,127 Hours,2010.0,\N,94,127 hours
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1105,1169,2016,2016,Zoolander 2,Paramount Pictures,Comedy,Original Screenplay,Live Action,Contemporary Fiction,50000000.0,...,5.534869e+07,zoolander 2,tt1608290,movie,Zoolander 2,Zoolander 2,2016.0,\N,101,zoolander 2
243,270,2016,2016,Zootopia,Walt Disney,Adventure,Original Screenplay,Digital Animation,Kids Fiction,150000000.0,...,1.005305e+09,zootopia,tt2948356,movie,Zootopia,Zootopia,2016.0,\N,108,zootopia
1577,1642,2010,2010,[Rec] 2,Magnolia Pictures,NaN,NaN,NaN,NaN,5600000.0,...,1.852777e+07,[rec] 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2473,3328,2017,2017,mother!,Paramount Pictures,Thriller/Suspense,Original Screenplay,Live Action,Contemporary Fiction,30000000.0,...,4.253108e+07,mother!,tt5109784,movie,Mother!,Mother!,2017.0,\N,121,mother!
1192,1256,2017,2017,xXx: Return of Xander Cage,Paramount Pictures,Action,Original Screenplay,Live Action,Contemporary Fiction,85000000.0,...,3.450334e+08,xxx: return of xander cage,tt1293847,movie,xXx: Return of Xander Cage,xXx: Return of Xander Cage,2017.0,\N,107,xxx: return of xander cage

In [554]:
nb_df

,Released,ReleasedWorldwide,Title,TheatricalDistributor,Genre,Source,ProductionMethod,CreativeType,ProductionBudget,Opening WeekendTheaters,MaximumTheaters,TheatricalEngagements,Opening WeekendRevenue,DomesticBox Office,Infl. Adj. Dom.Box Office,InternationalBox Office,WorldwideBox Office,TitleLower
0,2019,2019,Toy Story 4,Walt Disney,Adventure,Original Screenplay,Digital Animation,Kids Fiction,200000000.0,4575.0,4575.0,38194.0,120908065.0,434038008.0,434038008.0,639042321.0,1.073080e+09,toy story 4
1,2010,2010,Toy Story 3,Walt Disney,Adventure,Original Screenplay,Digital Animation,Kids Fiction,200000000.0,4028.0,4028.0,33699.0,110307189.0,415004880.0,481805411.0,653874642.0,1.068880e+09,toy story 3
2,2013,2013,Monsters University,Walt Disney,Adventure,Original Screenplay,Digital Animation,Kids Fiction,200000000.0,4004.0,4004.0,24656.0,82429469.0,268488329.0,302503449.0,474967481.0,7.434558e+08,monsters university
3,2011,2011,Cars 2,Walt Disney,Adventure,Original Screenplay,Digital Animation,Kids Fiction,200000000.0,4115.0,4115.0,25790.0,66135507.0,191450875.0,221146280.0,368704508.0,5.601554e+08,cars 2
4,2017,2017,Cars 3,Walt Disney,Adventure,Original Screenplay,Digital Animation,Kids Fiction,175000000.0,4256.0,4256.0,24083.0,53688680.0,152901115.0,156139821.0,230640254.0,3.835414e+08,cars 3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2475,2021,2021,The Little Things,Warner Bros.,Thriller/Suspense,Original Screenplay,Live Action,Contemporary Fiction,30000000.0,2171.0,2206.0,16242.0,4800000.0,15245157.0,15245157.0,14392476.0,2.963763e+07,the little things
2476,2021,2021,Judas and the Black Messiah,Warner Bros.,Drama,Based on Real Life Events,Live Action,Dramatization,26000000.0,1888.0,1906.0,12065.0,2070000.0,5453633.0,5453633.0,1576927.0,7.030560e+06,judas and the black messiah
2477,2021,2021,Nomadland,Searchlight Pictures,Drama,Based on Fiction Book/Short Story,Live Action,Contemporary Fiction,5000000.0,0.0,1200.0,2400.0,0.0,2180000.0,2180000.0,24852509.0,2.703251e+07,nomadland
2478,2021,2021,Profile,Focus Features,Thriller/Suspense,Based on Fiction Book/Short Story,Live Action,Contemporary Fiction,2300000.0,2033.0,2104.0,4743.0,730290.0,1744740.0,1744740.0,45716.0,1.790456e+06,profile
2479,2021,2021,Our Friend,Roadside Attractions,Drama,Based on Factual Book/Article,Live Action,Dramatization,10000000.0,543.0,818.0,2405.0,250000.0,657351.0,657351.0,56744.0,7.140950e+05,our friend

In [571]:
merged_df.to_csv('./data/merged_tidy.csv', encoding='utf-8')

In [567]:
merged_df = pd.read_csv('./data/merged_tidy.csv', encoding='utf-8')

In [577]:
mergedNotnull_df = merged_df.loc[merged_df.tconst.notnull()]

In [579]:
mergedNotnull_df.dropna(inplace=True)

<ipython-input-579-25e61cf7800c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mergedNotnull_df.dropna(inplace=True)

In [581]:
mergedNotnull_df.drop(columns=['Unnamed: 0'],inplace=True)

C:\Users\dsmith\anaconda3\envs\learn-env\lib\site-packages\pandas\core\frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [583]:
mergedNotnull_df.drop_duplicates(inplace=True)

<ipython-input-583-36575311c3dc>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mergedNotnull_df.drop_duplicates(inplace=True)

In [585]:
mergedNotnull_df.to_csv('./data/final_merged_tidy.csv', encoding='utf-8')

In [586]:
pd.read_csv('./data/final_merged_tidy.csv', encoding='utf-8')

,Unnamed: 0,Released,ReleasedWorldwide,Title,TheatricalDistributor,Genre,Source,ProductionMethod,CreativeType,ProductionBudget,...,WorldwideBox Office,TitleLower,tconst,titleType,primaryTitle,originalTitle,startYear,endYear,runtimeMinutes,primaryTitleLower
0,0,2019,2019,Toy Story 4,Walt Disney,Adventure,Original Screenplay,Digital Animation,Kids Fiction,200000000.0,...,1.073080e+09,toy story 4,tt1979376,movie,Toy Story 4,Toy Story 4,2019.0,\N,100,toy story 4
1,1,2010,2010,Toy Story 3,Walt Disney,Adventure,Original Screenplay,Digital Animation,Kids Fiction,200000000.0,...,1.068880e+09,toy story 3,tt0435761,movie,Toy Story 3,Toy Story 3,2010.0,\N,103,toy story 3
2,2,2013,2013,Monsters University,Walt Disney,Adventure,Original Screenplay,Digital Animation,Kids Fiction,200000000.0,...,7.434558e+08,monsters university,tt1453405,movie,Monsters University,Monsters University,2013.0,\N,104,monsters university
3,3,2011,2011,Cars 2,Walt Disney,Adventure,Original Screenplay,Digital Animation,Kids Fiction,200000000.0,...,5.601554e+08,cars 2,tt1216475,movie,Cars 2,Cars 2,2011.0,\N,106,cars 2
4,4,2017,2017,Cars 3,Walt Disney,Adventure,Original Screenplay,Digital Animation,Kids Fiction,175000000.0,...,3.835414e+08,cars 3,tt3606752,movie,Cars 3,Cars 3,2017.0,\N,102,cars 3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2624,2761,2021,2021,The Little Things,Warner Bros.,Thriller/Suspense,Original Screenplay,Live Action,Contemporary Fiction,30000000.0,...,2.963763e+07,the little things,tt10016180,movie,The Little Things,The Little Things,2021.0,\N,128,the little things
2625,2762,2021,2021,Judas and the Black Messiah,Warner Bros.,Drama,Based on Real Life Events,Live Action,Dramatization,26000000.0,...,7.030560e+06,judas and the black messiah,tt9784798,movie,Judas and the Black Messiah,Judas and the Black Messiah,2021.0,\N,126,judas and the black messiah
2626,2763,2021,2021,Nomadland,Searchlight Pictures,Drama,Based on Fiction Book/Short Story,Live Action,Contemporary Fiction,5000000.0,...,2.703251e+07,nomadland,tt9770150,movie,Nomadland,Nomadland,2020.0,\N,107,nomadland
2627,2764,2021,2021,Profile,Focus Features,Thriller/Suspense,Based on Fiction Book/Short Story,Live Action,Contemporary Fiction,2300000.0,...,1.790456e+06,profile,tt7826276,movie,Profile,Profile,2018.0,\N,106,profile
2628,2765,2021,2021,Our Friend,Roadside Attractions,Drama,Based on Factual Book/Article,Live Action,Dramatization,10000000.0,...,7.140950e+05,our friend,tt9608818,movie,Our Friend,Our Friend,2019.0,\N,124,our friend

In [590]:
imdbprinciplas_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46232106 entries, 0 to 46232105
Data columns (total 6 columns):
 #   Column      Dtype
---  ------      -----
 0   tconst      object
 1   ordering    int64
 2   nconst      object
 3   category    object
 4   job         object
 5   characters  object
dtypes: int64(1), object(5)
memory usage: 2.1+ GB

In [592]:
titleswprins_df = pd.merge(mergedNotnull_df, imdbprinciplas_df,  how='left', left_on=['tconst'], right_on = ['tconst'])

In [593]:
titleswprins_df.to_csv('./data/titleswprins.csv', encoding='utf-8')

In [596]:
titleswprins_df.head(10)

,Released,ReleasedWorldwide,Title,TheatricalDistributor,Genre,Source,ProductionMethod,CreativeType,ProductionBudget,Opening WeekendTheaters,...,originalTitle,startYear,endYear,runtimeMinutes,primaryTitleLower,ordering,nconst,category,job,characters
0,2019,2019,Toy Story 4,Walt Disney,Adventure,Original Screenplay,Digital Animation,Kids Fiction,200000000.0,4575.0,...,Toy Story 4,2019.0,\N,100,toy story 4,10.0,nm0566489,writer,original story by,\N
1,2019,2019,Toy Story 4,Walt Disney,Adventure,Original Screenplay,Digital Animation,Kids Fiction,200000000.0,4575.0,...,Toy Story 4,2019.0,\N,100,toy story 4,1.0,nm0000158,actor,\N,"[""Woody""]"
2,2019,2019,Toy Story 4,Walt Disney,Adventure,Original Screenplay,Digital Animation,Kids Fiction,200000000.0,4575.0,...,Toy Story 4,2019.0,\N,100,toy story 4,2.0,nm0000741,actor,\N,"[""Buzz Lightyear""]"
3,2019,2019,Toy Story 4,Walt Disney,Adventure,Original Screenplay,Digital Animation,Kids Fiction,200000000.0,4575.0,...,Toy Story 4,2019.0,\N,100,toy story 4,3.0,nm0001633,actress,\N,"[""Bo Peep""]"
4,2019,2019,Toy Story 4,Walt Disney,Adventure,Original Screenplay,Digital Animation,Kids Fiction,200000000.0,4575.0,...,Toy Story 4,2019.0,\N,100,toy story 4,4.0,nm0355024,actor,\N,"[""Forky""]"
5,2019,2019,Toy Story 4,Walt Disney,Adventure,Original Screenplay,Digital Animation,Kids Fiction,200000000.0,4575.0,...,Toy Story 4,2019.0,\N,100,toy story 4,5.0,nm2155757,director,\N,\N
6,2019,2019,Toy Story 4,Walt Disney,Adventure,Original Screenplay,Digital Animation,Kids Fiction,200000000.0,4575.0,...,Toy Story 4,2019.0,\N,100,toy story 4,6.0,nm0005124,writer,original story by,\N
7,2019,2019,Toy Story 4,Walt Disney,Adventure,Original Screenplay,Digital Animation,Kids Fiction,200000000.0,4575.0,...,Toy Story 4,2019.0,\N,100,toy story 4,7.0,nm0004056,writer,original story by,\N
8,2019,2019,Toy Story 4,Walt Disney,Adventure,Original Screenplay,Digital Animation,Kids Fiction,200000000.0,4575.0,...,Toy Story 4,2019.0,\N,100,toy story 4,8.0,nm1445746,writer,original story by,\N
9,2019,2019,Toy Story 4,Walt Disney,Adventure,Original Screenplay,Digital Animation,Kids Fiction,200000000.0,4575.0,...,Toy Story 4,2019.0,\N,100,toy story 4,9.0,nm0429069,writer,original story by,\N

In [598]:
titleswprins_df.columns

Index(['Released', 'ReleasedWorldwide', 'Title', 'TheatricalDistributor',
       'Genre', 'Source', 'ProductionMethod', 'CreativeType',
       'ProductionBudget', 'Opening WeekendTheaters', 'MaximumTheaters',
       'TheatricalEngagements', 'Opening WeekendRevenue', 'DomesticBox Office',
       'Infl. Adj. Dom.Box Office', 'InternationalBox Office',
       'WorldwideBox Office', 'TitleLower', 'tconst', 'titleType',
       'primaryTitle', 'originalTitle', 'startYear', 'endYear',
       'runtimeMinutes', 'primaryTitleLower', 'ordering', 'nconst', 'category',
       'job', 'characters'],
      dtype='object')

In [599]:
actors_movies_df = titleswprins_df[['Released','Title', 'DomesticBox Office', 'Infl. Adj. Dom.Box Office','tconst', 'nconst','ordering','category']]

In [602]:
actors_movies_df['category'].value_counts()

actor                  6062
producer               4336
writer                 3909
actress                3776
director               2707
composer               1314
cinematographer         944
editor                  499
self                    246
production_designer     148
archive_footage          15
archive_sound             1
Name: category, dtype: int64

In [606]:
options = ['actor', 'actress', 'director']
diract_mov_df = actors_movies_df.loc[actors_movies_df['category'].isin(options)]

In [608]:
diract_mov_df.sort_values(by=['nconst', 'Released'])

,Released,Title,DomesticBox Office,Infl. Adj. Dom.Box Office,tconst,nconst,ordering,category
19608,2015,Shanghai,46425.0,50444.0,tt1092634,nm0000084,2.0,actress
127,2011,Winnie the Pooh,26692846.0,30833091.0,tt1449283,nm0000092,3.0,actor
728,2011,The Big Year,7204138.0,8321549.0,tt1053810,nm0000092,4.0,actor
3223,2019,Arctic Dogs,5801249.0,5801249.0,tt4426464,nm0000092,4.0,actor
247,2010,Megamind,148415853.0,172280602.0,tt1001526,nm0000093,3.0,actor
...,...,...,...,...,...,...,...,...
12536,2019,After,12138565.0,12138565.0,tt8692378,nm9968166,2.0,actor
12538,2019,After,12138565.0,12138565.0,tt8692378,nm9968169,4.0,actor
12535,2019,After,12138565.0,12138565.0,tt8692378,nm9968170,1.0,actor
23740,2020,Seberg,448009.0,448009.0,tt1780967,nm9982380,3.0,actor
12511,2019,After,12138565.0,12138565.0,tt4126476,nm9982544,3.0,actress

GET ALL Movies based on Name of Actor

In [610]:
imdbnames_df[imdbnames_df.primaryName == 'Tom Hanks']

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
157,nm0000158,Tom Hanks,1956,\N,"producer,actor,soundtrack","tt0109830,tt0112384,tt0162222,tt0094737"

get nconst from imdbnames_df link with imdbprincipals on nconst get tconst to get movie and possibly call imdb_api 
calculate cr and wicar for each actor.

In [611]:
imdbprinciplas_df[imdbprinciplas_df.nconst == 'nm0000158']

,tconst,ordering,nconst,category,job,characters
679952,tt0080202,1,nm0000158,actor,\N,"[""Buffy Wilson"",""Kip Wilson""]"
716399,tt0084314,1,nm0000158,actor,\N,"[""Robbie Wheeling""]"
739536,tt0086927,1,nm0000158,actor,\N,"[""Rick Gassko""]"
750314,tt0088161,1,nm0000158,actor,\N,"[""Allen Bauer""]"
762387,tt0089543,1,nm0000158,actor,\N,"[""Richard""]"
...,...,...,...,...,...,...
44875058,tt9441662,8,nm0000158,archive_footage,\N,"[""Self""]"
45058410,tt9505358,3,nm0000158,archive_footage,\N,"[""Various Characters""]"
45161620,tt9541280,3,nm0000158,self,\N,"[""Self - Guest""]"
45624708,tt9701726,4,nm0000158,archive_footage,\N,"[""Self - Actor""]"
45848894,tt9779754,1,nm0000158,self,\N,"[""Self""]"